baseURL = 'https://gleaming-tapioca-63dc92.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anubis'

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
